name: Unittest

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        pip install flake8 mypy
        python -m pip install -r requirements-dev.txt
    - name: TESTING Typing
      run: python3.9 -m mypy .
    - name: PEP8 Test
      run: |
        python3.9 -m flake8 .